enum ScreenNameEnum {
  SPLASH_SCREEN = 'Splash',
  IntroScreen = 'Intro',
  ActivityFocusScreen = 'ActivityFocus',
  BiometricProfile = 'BiometricProfile',
  DefinePathScreen = 'DefinePath',
  Login = 'Login',
  Sinup = 'Signup',
  OtpScreen = 'Otp',

  TabNavigator = 'MainTabs',
  HomeTab = 'HomeTab',
  ExploreTab = 'ExploreTab',
  CoachTab = 'CoachTab',
  ProfileTab = 'ProfileTab',
  RanksTab = 'RanksTab',

  HomeScreen = 'Home',
  ExploreScreen = 'Explore',
  RanksScreen = 'Ranks',
  PrimaryFocusScreen = "PrimaryFocusScreen",
  FitnessDashboard = 'FitnessDashboard',
  MissionScreen = 'MissionScreen',
  FitnessProgress = 'FitnessProgress',
  ExerciseLibrary = 'ExerciseLibrary',
  BMICalculator = 'BMICalculator',
  HydrationGoal = 'HydrationGoal',
  IsolationCardio = 'IsolationCardio',
  Marketplace = 'Marketplace',
  MealPlanList = 'MealPlanList',
  MealRecommendation = 'MealRecommendation',
  SkinnyAIChat = 'SkinnyAIChat',
  SmartNotification = 'SmartNotification',
  WorkoutComplete = 'WorkoutComplete',
  WorkoutPlan = 'WorkoutPlan',
  ActiveReminders = 'ActiveReminders',
  TrainingReminder = 'TrainingReminder',
  WorkoutTime = 'WorkoutTime',
  WatchLock = "WatchLock",
  PremiumScreen = "PremiumScreen",
  FastingScreen = "FastingScreen",
  FastingProtocolScreen = "FastingProtocolScreen",
  ProfileSetup = 'Profile',
  EditProfile = 'EditProfile',
  PrivacyPolicy = 'PrivacyPolicy',
  NotificationsScreen = 'Notifications',
  NotificationsSetting = 'NotificationsSetting',
  FitnessProfileScreen = "FitnessProfileScreen",
  HydrationTipScreen = "HydrationTipScreen",
  // Backward-compatible aliases used by older auth/API code.
  DashBoardScreen = 'MainTabs',
  CreateNewPassword = 'Otp',
  PasswordReset = 'Otp',
  DELIVERY_DETAIL = 'WorkoutPlan',
}

export default ScreenNameEnum;
