import { StyleSheet, Platform } from 'react-native';
import { color } from '../../../constant';
import { hp } from '../../../utils/Constant';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: color.background,
  },
  headerGradient: {
    paddingBottom: 30,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  statImage: {
    height: 30,
    width: 30,
  },
  actionImage: {
    height: 24,
    width: 24,
    // marginLeft: 10,
  },
  headerContent: {
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  welcomeText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
  },
  userName: {
    color: color.white,
    fontSize: 24,
    fontWeight: '700',
    marginTop: 4,
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: 'rgba(255,255,255,0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 12,
  },
  onlineStatusContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#2A2A2A',
    marginHorizontal: 20,
    marginTop: 15,
    borderRadius: 30,
    paddingHorizontal: 5,
    borderWidth: 1,
    borderColor: '#23262F',
    height: 60
  },
  goButton: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  goText: {
    color: color.white,
    fontWeight: 'bold',
    fontSize: 12,
  },
  statusText: {
    color: color.primary,
    fontSize: 18,
    fontWeight: '600',
    marginRight: 15,
  },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginTop: 25,
  },
  statCard: {
    width: '32%',
    borderRadius: 20,
    padding: 15,
    borderWidth: 1,
    borderColor: '#393B48',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  statIconContainer: {
    width: 35,
    height: 35,
    borderRadius: 10,
    backgroundColor: 'rgba(255,255,255,0.05)',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  statLabel: {
    color: '#6F767E',
    fontSize: 10,
    fontWeight: '500',
  },
  statValue: {
    color: color.white,
    fontSize: 18,
    fontWeight: '700',
    marginTop: 4,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginTop: 30,
    marginBottom: 15,
  },
  sectionTitle: {
    color: color.white,
    fontSize: 20,
    fontWeight: '700',
  },
  viewAll: {
    color: color.primary,
    fontSize: 14,
    fontWeight: '500',
  },
  quickActionsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
  },
  actionCard: {
    width: '31%',
    borderRadius: 20,
    paddingVertical: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#393B48',
  },
  actionText: {
    color: color.white,
    fontSize: 12,
    fontWeight: '600',
    marginTop: 10,
    textAlign: 'center',
  },
  deliveryCard: {
    backgroundColor: '#FFFFFF14',
    marginHorizontal: 20,
    borderRadius: 25,
    padding: 20,
    marginBottom: 15,
    borderWidth: 1,
    borderColor: '#23262F',
  },
  cardTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  orderInfo: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconBox: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: 'rgba(76, 188, 166, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  orderId: {
    color: color.white,
    fontSize: 16,
    fontWeight: '700',
  },
  orderDate: {
    color: '#6F767E',
    fontSize: 12,
    marginTop: 2,
  },
  statusBadge: {
    color: color.primary,
    fontSize: 12,
    fontWeight: '600',
  },
  addressSection: {
    marginLeft: 5,
  },
  addressRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  addressLine: {
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  smallDot: {
    width: 2,
    height: 2,
    borderRadius: 1,
    backgroundColor: '#393B48',
    marginVertical: 2,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#6F767E',
    marginTop: 4,
  },
  dot1: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#6F767E',
    marginTop: 0,
  },
  addressTextContainer: {
    marginLeft: 15,
  },
  addressLabel: {
    color: '#6F767E',
    fontSize: 12,
  },
  addressText: {
    color: color.white,
    fontSize: 14,
    fontWeight: '500',
    marginTop: 2,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: '#0E101F',
    borderRadius: 15,
    padding: 5,
    marginVertical: 10,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 12,
  },
  tabText: {
    color: color.primary,
    fontSize: 14,
    fontWeight: '600',
  },
});
