export type ThemeMode = 'light' | 'dark';

export const rawColors = {
  black: '#000000',
  white: '#FFFFFF',
  transparent: 'transparent',
  blue: '#236CED',
  blueStrong: '#0066FF',
  blueSoft: '#BFC7FF',
  coral: '#FFB19F',
  coralText: '#4C271D',
  danger: '#FF4B4B',
  success: '#00B894',
  successBright: '#2ECC71',
  warning: '#FFB000',
  gold: '#F3B748',
  purple: '#7B4DFF',
  pink: '#D64FA5',
  protein: '#2CC59D',
  carb: '#56CCF2',
  fat: '#F2994A',
  overlayDark: 'rgba(0,0,0,0.55)',
  overlayStrong: 'rgba(0,0,0,0.75)',
} as const;

export const lightTheme = {
  mode: 'light' as const,
  colors: {
    background: 'black',
    surface: '#FFFFFF',
    surfaceElevated: '#FFFFFF',
    surfaceMuted: '#EEF1F7',
    card: '#FFFFFF',
    cardAlt: '#F8F9FC',
    input: '#FFFFFF',
    text: '#101828',
    textPrimary: '#101828',
    textSecondary: '#5E6678',
    textMuted: '#8D93A3',
    textInverse: rawColors.white,
    icon: '#5E6678',
    iconMuted: '#8D93A3',
    border: '#E2E7F0',
    borderSoft: '#EEF1F7',
    primary: rawColors.blue,
    primaryDark: rawColors.blueStrong,
    primarySoft: '#E7EEFF',
    accent: rawColors.coral,
    accentText: rawColors.coralText,
    tabBar: '#FFFFFF',
    tabInactive: '#8D93A3',
    tabActive: rawColors.blue,
    button: rawColors.white,
    buttonText: rawColors.black,
    danger: rawColors.danger,
    success: rawColors.success,
    warning: rawColors.warning,
    placeholder: '#9BA2B1',
    shadow: '#101828',
    overlay: 'rgba(16,24,40,0.45)',
    overlayStrong: rawColors.overlayStrong,
    transparent: rawColors.transparent,
    statusBar: '#F6F7FB',
    statusBarStyle: 'dark-content' as const,
    avatarBg: '#E4E8F0',
    divider: '#E8ECF3',
    modal: '#FFFFFF',
    chip: '#EEF1F7',
    disabled: '#D7DCE6',
    rankSideAvatar: '#E7C087',
    rankSideBorder: '#49BDF7',
    rankGoldGlow: 'rgba(255,226,88,0.18)',
    rankGoldShadow: '#FFE85C',
    rankGold: rawColors.gold,
    rankBlueBadge: '#3E68F2',
    rankPink: rawColors.pink,
    rankMeAvatar: '#343C8D',
    streakFire: '#6A2D17',
    streakFireActive: '#273A74',
  },
} as const;

export const darkTheme = {
  mode: 'dark' as const,
  colors: {
    background: 'black',
    surface: '#0B1220',
    surfaceElevated: '#111827',
    surfaceMuted: '#171923',
    card: '#101116',
    cardAlt: '#161F2E',
    input: '#010A16',
    text: '#FFFFFF',
    textPrimary: '#F8FAFC',
    textSecondary: '#B6B7C2',
    textMuted: '#8D8FA1',
    textInverse: '#101010',
    icon: '#DADDF2',
    iconMuted: '#6F767E',
    border: '#252733',
    borderSoft: 'rgba(255,255,255,0.08)',
    primary: rawColors.blue,
    primaryDark: rawColors.blueStrong,
    primarySoft: '#10131F',
    accent: rawColors.coral,
    accentText: rawColors.coralText,
    tabBar: '#090909',
    tabInactive: '#8D8FA1',
    tabActive: rawColors.blueSoft,
    button: rawColors.white,
    buttonText: rawColors.black,
    danger: rawColors.danger,
    success: rawColors.success,
    warning: rawColors.warning,
    placeholder: '#A7A7A8',
    shadow: rawColors.black,
    overlay: rawColors.overlayDark,
    overlayStrong: rawColors.overlayStrong,
    transparent: rawColors.transparent,
    statusBar: '#050B18',
    statusBarStyle: 'light-content' as const,
    avatarBg: '#1E293B',
    divider: 'rgba(255,255,255,0.05)',
    modal: '#111827',
    chip: 'rgba(255,255,255,0.05)',
    disabled: '#343846',
    rankSideAvatar: '#E7C087',
    rankSideBorder: '#49BDF7',
    rankGoldGlow: 'rgba(255,226,88,0.18)',
    rankGoldShadow: '#FFE85C',
    rankGold: rawColors.gold,
    rankBlueBadge: '#3E68F2',
    rankPink: rawColors.pink,
    rankMeAvatar: '#343C8D',
    streakFire: '#6A2D17',
    streakFireActive: '#273A74',
  },
} as const;

export const themes = {
  light: lightTheme,
  dark: darkTheme,
} as const;

export type AppTheme = typeof lightTheme | typeof darkTheme;
export type AppThemeColors = AppTheme['colors'];

export const color = {
  baground: rawColors.coral,
  buttonColor: darkTheme.colors.button,
  black: rawColors.black,
  white: rawColors.white,
  borderColor: lightTheme.colors.borderSoft,
  borderPrimary: '#081041',
  grey: lightTheme.colors.textMuted,
  primary: rawColors.blue,
  primaryDark: rawColors.blueStrong,
  onBoarding: '#FFF0E3',
  red: rawColors.danger,
  placeholderText: darkTheme.colors.placeholder,
  protein: rawColors.protein,
  carb: rawColors.carb,
  fat: rawColors.fat,
  primaryLight: rawColors.blueSoft,
  secondary: '#FF6584',
  background: darkTheme.colors.background,
  cardBackground: darkTheme.colors.card,
  textPrimary: darkTheme.colors.textPrimary,
  textSecondary: darkTheme.colors.textSecondary,
  textLight: darkTheme.colors.textMuted,
  border: darkTheme.colors.border,
  success: rawColors.success,
  transparent: rawColors.transparent,
  overlay: rawColors.overlayDark,
  overlayStrong: rawColors.overlayStrong,
  danger: rawColors.danger,
  warning: rawColors.warning,
  accent: rawColors.coral,
  accentText: rawColors.coralText,
} as const;
