export default {
  TrialBlackItalic: 'TT Neoris Trial Black Italic',
  TrialBlack:"TT Neoris Trial Black",
  MonolithRegular:"Monolith Regular",
  TrialBoldItalic:"TT Neoris Trial Bold Italic",
  TrialBold:"TT Neoris Trial Bold",
  TrialDemiBoldItalic:"TT Neoris Trial DemiBold Italic",
  TrialDemiBold:"TT Neoris Trial DemiBold",
  TrialExtraBoldItalic:"TT Neoris Trial ExtraBold Italic",
  TrialExtraBold:"TT Neoris Trial ExtraBold",
  TrialExtraLight:"TT Neoris Trial ExtraLight",
  TrialExtraLightItalic:"TT Neoris Trial ExtraLight Italic",
  TrialHairlineItalic:"TT Neoris Trial Hairline Italic",
  TrialItalic:"TT Neoris Trial Italic",
  TrialHairline:"TT Neoris Trial Hairline",
  TrialLight:"TT Neoris Trial Light",
  LightItalic:"TT Neoris Trial Light Italic",
  TrialMediumItalic:"TT Neoris Trial Medium Italic",
  TrialMedium:"TT Neoris Trial Medium",
  TrialRegular:"TT Neoris Trial Regular",
  TrialThinItalic:"TT Neoris Trial Thin Italic",
  TrialVariable:"TT Neoris Trial Variable",
  TrialThin:"TT Neoris Trial Thin",
  TrialSemiBold:"Panton-Trial-SemiBold",
     
  };