export default {
  appLogo: require('./images/appLogo.png'),
  appLogo1: require('./images/loginTop.png'),
  bag: require('./images/bag.png'),
  docCircle: require('./images/docCircle.png'),
  first1: require('./images/first1.png'),
  bag1: require('./images/bag1.png'),
  aboutus: require('./images/aboutus.png'),
  editp: require('./images/editp.png'),
  REMOVE: require('./images/REMOVE.png'),
  P1: require('./images/P1.png'),
  officeImg: require('./images/office.png'),
  privacy: require('./images/privacy.png'),
  banner1: require('./images/banner1.png'),
  chatMt: require('./images/chatMt.png'),
  Photoroom: require('./images/Photoroom.png'),
  Textphone: require('./images/Textphone.png'),
  Editpen: require('./images/Editpen.png'),
  lock: require('./images/lock.png'),
  Textprofile: require('./images/Textprofile.png'),
  eye: require('./images/hide.png'),
  mess: require('./images/mess.png'),
  search: require('./images/search1.png'),
  helpPrva: require('./images/helpPrva.png'),
  sp2: require('./images/onboarding.png'),
  right: require('./images/black.png'),
  prfile: require('./images/prfile.png'),
  back: require('./images/back.png'),
  logout: require('./images/logout.png'),
  userLogo: require('./images/userLogo.png'),
  no1: require('./images/no1.png'),
  driver: require('./images/driver.png'),
  global: require('./images/global.png'),
  language: require('./images/language.png'),
succesfuly: require('./images/success.png'),
menu: require('./images/menu.png'),
profile: require('./images/profile.png'),
video: require('./images/video.png'),
clock: require('./images/clock.png'),
logout1:require('./images/logout1.png'),
terms:require('./images/terms.png'),
support:require('./images/support.png'),
info:require('./images/info.png'),
lock1:require('./images/lock1.png'),
service:require('./images/service.png'),
dummy:require('./images/dummy.png'),
user:require('./images/user.png'),
company:require('./images/company.png'),
multiUser:require('./images/multiUser.png'),



}; 